export { default as Navbar } from './Navbar'
export { default as Bike } from './Bike'
export { default as Home } from './Home'
export { default as Features } from './Features'
export { default as About } from './About'
export { default as Footer } from './Footer'